[package]
name = "all-days"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.12.0"
num = "0.4.1"

[[bin]]
name = "day_1"
path = "src/day_1.rs"
test = true

[[bin]]
name = "day_2"
path = "src/day_2.rs"
test = true

[[bin]]
name = "day_3"
path = "src/day_3.rs"
test = true

[[bin]]
name = "day_4"
path = "src/day_4.rs"
test = true

[[bin]]
name = "day_5"
path = "src/day_5.rs"
test = true

[[bin]]
name = "day_6"
path = "src/day_6.rs"
test = true

[[bin]]
name = "day_7"
path = "src/day_7.rs"
test = true

[[bin]]
name = "day_8"
path = "src/day_8.rs"
test = true